name: Jest Test

on:
  push:
    branches: ["master", "main", "develop"]
  pull_request:
    branches: ["master", "main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Test using jest
        run: npm test
